baseURL = "https://pfeister.dev/"
languageCode = "en-us"
title = "Paul Pfeister"
theme = "hugo-coder-nord"

[params]
    shortbio = "Hello there..."
	author = "Paul Pfeister"
	info = "SSB3b3JrIGluIG9mZmVuc2l2ZSBzZWN1cml0eS4K"
	description = "Paul Pfeister's personal website"
	keywords = "paul pfeister,network,it,cybersecurity,infosec,pentesting, penetration test"
	colorScheme = "auto"

[[params.social]]
	name = "Github"
	icon = "fa fa-github fa-2x"
	weight = 1
	url = "https://github.com/paulpfeister"
	target = "_blank"
[[params.social]]
	name = "LinkedIn"
	icon = "fa fa-linkedin fa-2x"
	weight = 3
	url = "https://www.linkedin.com/in/paulpfeister"
	target = "_blank"

[[menu.main]]
	name = "About"
	weight = 1
	url = "about/"
#[[menu.main]]
#	name = "Blog"
#	weight = 2
#	url = "posts/"
#[[menu.main]]
#    name = "Contact"
#    weight = 5
#    url = "contact/"

[markup.goldmark.renderer]
unsafe = true
